// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Path/EntityFileValue.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Normandy.Legacy.Client.Protos {

  /// <summary>Holder for reflection information generated from Path/EntityFileValue.proto</summary>
  public static partial class EntityFileValueReflection {

    #region Descriptor
    /// <summary>File descriptor for Path/EntityFileValue.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntityFileValueReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpQYXRoL0VudGl0eUZpbGVWYWx1ZS5wcm90bxIJUHJvdG9IZXZvIjoKD0Vu",
            "dGl0eUZpbGVWYWx1ZRIKCgJsbhgBIAEoCRIKCgJ4bhgCIAEoCRIPCgdjb250",
            "ZXh0GAMgASgJIhoKDEVudGl0eUZpbGVJZBIKCgJzbhgBIAEoBSIsChlFbnRp",
            "dHlGaWxlVmFsdWVfWXVhblNodUp1Eg8KB3NvcnRzdHIYASABKAlCGqoCF0hl",
            "dm8uQ29yZS5TaGFyZWQuUHJvdG9zYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Normandy.Legacy.Client.Protos.EntityFileValue), global::Normandy.Legacy.Client.Protos.EntityFileValue.Parser, new[]{ "Ln", "Xn", "Context" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Normandy.Legacy.Client.Protos.EntityFileId), global::Normandy.Legacy.Client.Protos.EntityFileId.Parser, new[]{ "Sn" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Normandy.Legacy.Client.Protos.EntityFileValue_YuanShuJu), global::Normandy.Legacy.Client.Protos.EntityFileValue_YuanShuJu.Parser, new[]{ "Sortstr" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///板块内容
  /// </summary>
  public sealed partial class EntityFileValue : pb::IMessage<EntityFileValue> {
    private static readonly pb::MessageParser<EntityFileValue> _parser = new pb::MessageParser<EntityFileValue>(() => new EntityFileValue());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityFileValue> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Normandy.Legacy.Client.Protos.EntityFileValueReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityFileValue() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityFileValue(EntityFileValue other) : this() {
      ln_ = other.ln_;
      xn_ = other.xn_;
      context_ = other.context_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityFileValue Clone() {
      return new EntityFileValue(this);
    }

    /// <summary>Field number for the "ln" field.</summary>
    public const int LnFieldNumber = 1;
    private string ln_ = "";
    /// <summary>
    ///板块长名称,即ln
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Ln {
      get { return ln_; }
      set {
        ln_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "xn" field.</summary>
    public const int XnFieldNumber = 2;
    private string xn_ = "";
    /// <summary>
    ///选股问句,即xn
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Xn {
      get { return xn_; }
      set {
        xn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "context" field.</summary>
    public const int ContextFieldNumber = 3;
    private string context_ = "";
    /// <summary>
    ///股票列表，即stocklist
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Context {
      get { return context_; }
      set {
        context_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityFileValue);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityFileValue other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ln != other.Ln) return false;
      if (Xn != other.Xn) return false;
      if (Context != other.Context) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Ln.Length != 0) hash ^= Ln.GetHashCode();
      if (Xn.Length != 0) hash ^= Xn.GetHashCode();
      if (Context.Length != 0) hash ^= Context.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Ln.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Ln);
      }
      if (Xn.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Xn);
      }
      if (Context.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Context);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Ln.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ln);
      }
      if (Xn.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Xn);
      }
      if (Context.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Context);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityFileValue other) {
      if (other == null) {
        return;
      }
      if (other.Ln.Length != 0) {
        Ln = other.Ln;
      }
      if (other.Xn.Length != 0) {
        Xn = other.Xn;
      }
      if (other.Context.Length != 0) {
        Context = other.Context;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Ln = input.ReadString();
            break;
          }
          case 18: {
            Xn = input.ReadString();
            break;
          }
          case 26: {
            Context = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///板块id
  /// </summary>
  public sealed partial class EntityFileId : pb::IMessage<EntityFileId> {
    private static readonly pb::MessageParser<EntityFileId> _parser = new pb::MessageParser<EntityFileId>(() => new EntityFileId());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityFileId> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Normandy.Legacy.Client.Protos.EntityFileValueReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityFileId() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityFileId(EntityFileId other) : this() {
      sn_ = other.sn_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityFileId Clone() {
      return new EntityFileId(this);
    }

    /// <summary>Field number for the "sn" field.</summary>
    public const int SnFieldNumber = 1;
    private int sn_;
    /// <summary>
    ///板块名称，sn
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Sn {
      get { return sn_; }
      set {
        sn_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityFileId);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityFileId other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sn != other.Sn) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Sn != 0) hash ^= Sn.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Sn != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Sn);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Sn != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Sn);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityFileId other) {
      if (other == null) {
        return;
      }
      if (other.Sn != 0) {
        Sn = other.Sn;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Sn = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///额外信息存储
  /// </summary>
  public sealed partial class EntityFileValue_YuanShuJu : pb::IMessage<EntityFileValue_YuanShuJu> {
    private static readonly pb::MessageParser<EntityFileValue_YuanShuJu> _parser = new pb::MessageParser<EntityFileValue_YuanShuJu>(() => new EntityFileValue_YuanShuJu());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityFileValue_YuanShuJu> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Normandy.Legacy.Client.Protos.EntityFileValueReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityFileValue_YuanShuJu() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityFileValue_YuanShuJu(EntityFileValue_YuanShuJu other) : this() {
      sortstr_ = other.sortstr_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityFileValue_YuanShuJu Clone() {
      return new EntityFileValue_YuanShuJu(this);
    }

    /// <summary>Field number for the "sortstr" field.</summary>
    public const int SortstrFieldNumber = 1;
    private string sortstr_ = "";
    /// <summary>
    ///多个板块的展示顺序的排序号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sortstr {
      get { return sortstr_; }
      set {
        sortstr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityFileValue_YuanShuJu);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityFileValue_YuanShuJu other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sortstr != other.Sortstr) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Sortstr.Length != 0) hash ^= Sortstr.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Sortstr.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Sortstr);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Sortstr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sortstr);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityFileValue_YuanShuJu other) {
      if (other == null) {
        return;
      }
      if (other.Sortstr.Length != 0) {
        Sortstr = other.Sortstr;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Sortstr = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
